# Generated by Django 3.2.13 on 2022-07-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.TextField(verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Blocked user'), (2, 'Whitelist user')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='top_credit',
            field=models.FloatField(default=0.0, verbose_name='Top credit'),
        ),
    ]
