# Generated by Django 3.2.13 on 2022-07-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220705_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Value'),
        ),
    ]
