# Generated by Django 3.2.13 on 2022-07-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_statistics_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_forget_code',
            field=models.IntegerField(default=0, verbose_name='Total forget code'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_recieved_list',
            field=models.IntegerField(default=0, verbose_name='Tota received list'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_reserved_food',
            field=models.IntegerField(default=0, verbose_name='Total reserved food'),
        ),
    ]
