# Generated by Django 3.2.13 on 2022-07-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_statistics_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Session'),
        ),
    ]
