# Generated by Django 3.2.13 on 2022-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220710_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user_agent',
            field=models.CharField(max_length=256, null=True, verbose_name='User agent'),
        ),
    ]
