# Generated by Django 3.2.13 on 2022-07-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_session_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram ID'),
        ),
    ]
