# Generated by Django 4.0.6 on 2022-07-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220714_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Blocked user'), (2, 'Whitelist user')], default=0, verbose_name='Status'),
        ),
    ]
