# Generated by Django 3.2.13 on 2022-06-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_used', models.DateTimeField(auto_now_add=True, verbose_name='First Used Time')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Last Used Time')),
                ('full_name', models.TextField(verbose_name='Text')),
                ('stu_number', models.TextField(verbose_name='Student number')),
                ('password', models.TextField(verbose_name='Password')),
                ('count_of_used', models.IntegerField(verbose_name='count of used')),
                ('credit', models.FloatField(verbose_name='Credit')),
                ('top_credit', models.FloatField(verbose_name='Top credit')),
                ('status', models.IntegerField(choices=[('normal', 'Normal'), ('blocked', 'Blocked user'), ('whited', 'White listed user')], default='normal')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_used', models.DateTimeField(auto_now_add=True, verbose_name='First Used Time')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Last Used Time')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.CharField(max_length=256, null=True, verbose_name='User agent')),
                ('path', models.CharField(max_length=256, null=True, verbose_name='Url path')),
                ('is_admin_panel', models.BooleanField(default=False, verbose_name='Is admin panel')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'visitor',
                'verbose_name_plural': 'visitors',
            },
        ),
    ]
