# Generated by Django 3.2.13 on 2022-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220705_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='value',
            field=models.BigIntegerField(default=0, verbose_name='Value'),
        ),
    ]
