# Generated by Django 3.2.13 on 2022-07-10 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220710_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='first_used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='First Used Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='last_used',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Used Time'),
        ),
    ]
