# Generated by Django 3.2.13 on 2022-07-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_session_telegram_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username'),
        ),
    ]
