name: Example CI Django & Postgres Tests

# Controls when the workflow will run
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: boostan
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install requirements
        env:
          DJANGO_DEBUG: false
          DEBUG: false
          DJANGO_SECRET_KEY: "secretsecretsecretsecret123456"
          DJANGO_SETTINGS_MODULE: "config.settings.production"
          DJANGO_ALLOWED_HOSTS: "*"
          DJANGO_ADMIN_URL: "admin/"
          DATABASE_URL: "postgres://postgres:postgres@127.0.0.1:5432/$POSTGRES_DB"
          BOOSTAN_USERNAME: ${{secrets.BOOSTAN_USERNAME}}
          BOOSTAN_PASSWORD: ${{secrets.BOOSTAN_PASSWORD}}
        run: |
          pip install -r requirements.txt && pip install -r requirements/local.txt
      - name: Collect statics
        run: |
          python manage.py collectstatic --noinput  
      - name: Make migrations
        run: |
          python manage.py makemigrations
      - name: Migrate
        run: |
          python manage.py migrate
      - name: Run Tests
        run: |
          python manage.py test api
